spring:
  application:
    name: spring-cloud-alibaba-sentinel
  cloud:
    sentinel:
      transport:
        #端口配置会在应用对应的机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互。
        #比如 Sentinel 控制台添加了一个限流规则，会把规则数据 push 给这个 Http Server 接收，
        #Http Server 再将规则注册到 Sentinel 中
        port: 8719
        #调用接口后才会生效
        dashboard: 127.0.0.1:8080
      datasource:
        da1:
          nacos:
            server-addr: 124.220.50.39:8848
            data-id: spring-cloud-alibaba-sentinel-flow
            rule-type: flow
        da2:
          nacos:
            server-addr: 124.220.50.39:8848
            data-id: spring-cloud-alibaba-sentinel-degrade
            rule-type: degrade
server:
  port: 9180
demo:
  log:
    enable-stdout: false
